### ISSUE TITLE
Variable name mismatch?

### ISSUE THREAD

**Issue by xme** [AssuranceMaladieSec/CertStreamMonitor#16]
The config sample refers to 'SearchKeywords' but the code refers to 'SearchString'. Mismatch?

**Comment by xme** [comment]
Nevermind... Mistake on my side :(

**Comment by cbrocas** [comment]
FTR it is our code that is inconsistent in this case: we [effectively map](https://github.com/AssuranceMaladieSec/CertStreamMonitor/blob/master/utils/confparser.py#L23) the config file parameter 'SearchKeywords' to the internal 'SearchString' variable name :-( 

Code needs patching to be aligned with the (consistent) config parameters to internal var names mapping applied to all others config parameters.

**Comment by cbrocas** [comment]
Fixed (https://github.com/AssuranceMaladieSec/CertStreamMonitor/commit/87e64641af089f24e2b0d8e9bd28a59c95135f31): the 'SearchKeywords' config file parameter is now mapped to the internal 'SearchKeywords' variable name.
