### ISSUE TITLE
Create a notification feature in addition to export results to a JSON file.

### ISSUE THREAD

**Issue by cbrocas** [AssuranceMaladieSec/CertStreamMonitor#17]
Maybe, it would be interesting to create a feature allowing us to push results found by `scanhost.py` script (currently only stored on disk as JSON files) to : 

- a messaging system like Slack/Rocket/Discord/etc
- a mailbox through SMTP mail.

A python package to look at: [https://github.com/caronc/apprise](https://github.com/caronc/apprise)

**Comment by cbrocas** [comment]
It is a work in progress. Email is working :-)

**Comment by xme** [comment]
It could also be interesting to get a JSON output from the main script and not only scanhost.py... To load the JSON output to 3rd party tools... My $0.02.

**Comment by cbrocas** [comment]
If the JSON file is generated by the certstreammonitor.py script, it means that you may have a notification in your 3rd party tool for a threat that is not already up (possibly no IP address, no AS info etc).

**Comment by cbrocas** [comment]
Maybe having a switch at certstreammonitor.py level. But it implies some code refactoring: test & get AS information, test for UP or not etc are currently located in scanhost.py script. Will speak about all of this with @ThDamon :-)

**Comment by xme** [comment]
For me, the idea would be to merge both scripts into a unique one!

**Comment by cbrocas** [comment]
It deserves some discussions ;-)

**Comment by cbrocas** [comment]
New PR joined: https://github.com/AssuranceMaladieSec/CertStreamMonitor/pull/18
