### ISSUE TITLE
Keywords Detection Threshold returns search results more than the given value

### ISSUE THREAD

**Issue by pravarag** [AssuranceMaladieSec/CertStreamMonitor#19]
I've given Detection Threshold as 1 in the config file for the search string value `paypal|apple|account|secure|login` . Where it should return me results like: `apps.bmwkey.account.com`, it's returning me results like `account.bmwkey.onubisecure.com` as well. I feel, Detection Threshold is not able to detect the frequency of entered value and `re.findall()` in  `print_callback()` inside `CertStreamMonitor.py`, is returning for all the matched patterns.

**Comment by cbrocas** [comment]
First, sorry for the delay!
The threshold of 1 only says that if the script finds one of search string members in the complete hostname string, it will prompt the hostname. No matter where it locates inside the hostname. 
In your example, `account`is present in the two hostnames `apps.bmwkey.account.com` and `account.bmwkey.onubisecure.com`. It is so logical that `CertStreamMonitor.py` detects these 2 hostnames (with a threshhold of 1 and your search string value).
