### ISSUE TITLE
scanhost.py continuously scanning unreachable sites

### ISSUE THREAD

**Issue by xme** [AssuranceMaladieSec/CertStreamMonitor#22]
I see in the scanhost.py source code the following comment:

`# if the site is UP, we log the timestamp in the database in order to not reprocess it`

I've plenty of sites that can't be checked because HTTPS is simply not available (ex: SMTP relays). They remain "unscanned" in the DB and are processed again and again. Do you have a way to avoid this? Ex: keep a counter and when the site has been unsuccessfully tested 'x' times, mark it as "processed"? What do you think?

**Comment by ThDamon** [comment]
Good idea! We probably gonna play with the _StillInvestig_ DB's column  and had a configuration variable for the number of days before stop the entry scan if it is still NULL.

**Comment by xme** [comment]
Look sufficient to me! I'll also have a look at the code and try to patch/submit something in this way...

**Comment by ThDamon** [comment]
We pushed some code with this new feature embedded (https://github.com/AssuranceMaladieSec/CertStreamMonitor/commit/0cbd5ad09a21d6c4aec391316149efefe97c5d8e), it's based on number of days you want to monitor an host. After that, scanhost.py will stop monitoring this hostname and the date when monitoring is stopped is added into database.
