### ISSUE TITLE
The SAN is always empty

### ISSUE THREAD

**Issue by mda01** [AssuranceMaladieSec/CertStreamMonitor#30]
Due to the lines 138-155 of CertStreamMonitor.py, the SAN is always empty and the database contains an empty column.

**Comment by cbrocas** [comment]
Effectively, SAN column use has been deprecated after we decided to extract each hostname from SAN to generate one DB record per hostname. Due to this change, the SAN information was no more relevant.
But you are right we do need to change the DB schema to drop the SAN column out of it.

**Comment by cbrocas** [comment]
Closes this issue on the requirement for us to change, one day, the DB schema.
