### ISSUE TITLE
Docker packages and distro versions issues

### ISSUE THREAD

**Issue by t4d** [AssuranceMaladieSec/CertStreamMonitor#32]
The docker files need to be upgraded (and versions fixed), it does not run anymore.

**Comment by xme** [comment]
Does it ring a bell to you? I've this now...

[ERROR:websocket] 2021-06-10 04:56:51,338 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7f3c27dac1d0>>: 'chain'

**Comment by ThDamon** [comment]
Yes, you should pull last changes, it should be ok now.

**Comment by xme** [comment]
Tx, worked like a charm (Needed to fix some Dockerfile issues) but my docker is back in business!

**Comment by ThDamon** [comment]
(pouce en l'air) I close this issue.
